version: '3.8'

services:
  web:
    build: .
    container_name: mail
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mail
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    container_name: mail_project_celery
    command: python -m celery -A mail_project worker
    volumes:
      - .:/mail
    depends_on:
      - web
      - redis
  redis:
    image: redis